<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ashishwadhwa-PC" name="Module9_TestNG.TestNG_Sample" tests="3" failures="0" timestamp="13 Oct 2019 12:20:58 GMT" time="3.121" errors="1">
  <testcase name="openingBrowser" time="0.014" classname="Module9_TestNG.TestNG_Sample"/>
  <testcase name="clickButton" time="0.003" classname="Module9_TestNG.TestNG_Sample"/>
  <testcase name="validateObject" time="3.104" classname="Module9_TestNG.TestNG_Sample">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.validateObject() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.validateObject() didn't finish within the time-out 3000
]]>
    </error>
  </testcase> <!-- validateObject -->
</testsuite> <!-- Module9_TestNG.TestNG_Sample -->
